import { build } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
const bundle = await build({entryPoints:['tools/push-crypto.mjs'],bundle:true,write:false,format:'iife',globalName:'MftnbPushCrypto',target:'es2020',minify:true,legalComments:'inline'});
const source = ['// Generated by npm run build:push. Edit backend/*.gs and tools/push-crypto.mjs.\n',
  await readFile('backend/forms.gs','utf8'), await readFile('backend/customer-email.gs','utf8'), await readFile('backend/owner-notifications.gs','utf8'),
  '\n// @noble/curves 2.4.0 + @noble/hashes; MIT notices: backend/THIRD-PARTY-LICENSES.txt\n',bundle.outputFiles[0].text].join('\n');
await writeFile('apps_script.gs',source);
await writeFile('backend/THIRD-PARTY-LICENSES.txt',
  '@noble/curves\n'+await readFile('node_modules/@noble/curves/LICENSE','utf8')+'\n@noble/hashes\n'+await readFile('node_modules/@noble/hashes/LICENSE','utf8'));
